# Clave única del proyecto y metadatos
sonar.projectKey=Canchas-Deportivas
sonar.projectName=Canchas Deportivas
sonar.projectVersion=1.0.0

# Carpetas de código fuente (Frontend y Backend en un solo análisis)
sonar.sources=frontend/Front-CanchasDeportivas/src,backend/Back-CanchasDeportivas/src

# Exclusiones globales del análisis
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/*.spec.ts

# Identificación de tests
sonar.tests=backend/Back-CanchasDeportivas/test,frontend/Front-CanchasDeportivas/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Codificación y TypeScript
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=backend/Back-CanchasDeportivas/tsconfig.json